#ifndef PCBWRITER_CTRLREQ_H
#define PCBWRITER_CTRLREQ_H

#define REQ_SET_SPEED 0x80
#define REQ_ENABLE_DEBUG_OUT 0x81

#define REQ_SET_PERSISTENT_FLASH 0x82
#define REQ_GET_PERSISTENT_FLASH 0x83

#endif
