#ifndef PCBWRITER_CTRLREQ_H
#define PCBWRITER_CTRLREQ_H

#define REQ_SET_SPEED 0x80
#define REQ_ENABLE_DEBUG_OUT 0x81

#define REQ_SET_PERSISTENT_FLASH 0x82
#define REQ_GET_PERSISTENT_FLASH 0x83

#define REQ_GET_STEPPER_STATUS 0x90
#define REQ_HOME_STEPPER 0x91
#define REQ_MOVE_STEPPER 0x92
#define REQ_STEPPER_OFF 0x93

#define REQ_CAN_SEND 0xC0

#endif
