#ifndef PCBWRITER_PINS_H
#define PCBWRITER_PINS_H

// DEBUG0_OUT: PB0
#define DEBUG0_OUT_PORT GPIOB
#define DEBUG0_OUT_PIN  GPIO0

// DEBUG1_OUT: PB1
#define DEBUG1_OUT_PORT GPIOB
#define DEBUG1_OUT_PIN  GPIO1

#endif
